// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	shoppingdetail "AltaStore/modules/shoppingdetail"

	mock "github.com/stretchr/testify/mock"
)

// RepoShoppingDetail is an autogenerated mock type for the RepoShoppingDetail type
type RepoShoppingDetail struct {
	mock.Mock
}

// GetShopCartDetailById provides a mock function with given fields: id
func (_m *RepoShoppingDetail) GetShopCartDetailById(id string) (*[]shoppingdetail.ShopCartDetailItemWithProductName, error) {
	ret := _m.Called(id)

	var r0 *[]shoppingdetail.ShopCartDetailItemWithProductName
	if rf, ok := ret.Get(0).(func(string) *[]shoppingdetail.ShopCartDetailItemWithProductName); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]shoppingdetail.ShopCartDetailItemWithProductName)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
