// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	shopping "AltaStore/business/shopping"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// DeleteItemInShopCart provides a mock function with given fields: cartId, productid, userid
func (_m *Service) DeleteItemInShopCart(cartId string, productid string, userid string) error {
	ret := _m.Called(cartId, productid, userid)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(cartId, productid, userid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetShopCartDetailById provides a mock function with given fields: id, userid
func (_m *Service) GetShopCartDetailById(id string, userid string) (*shopping.ShopCartDetail, error) {
	ret := _m.Called(id, userid)

	var r0 *shopping.ShopCartDetail
	if rf, ok := ret.Get(0).(func(string, string) *shopping.ShopCartDetail); ok {
		r0 = rf(id, userid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*shopping.ShopCartDetail)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(id, userid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetShoppingCartByUserId provides a mock function with given fields: userid
func (_m *Service) GetShoppingCartByUserId(userid string) (*shopping.ShoppCart, error) {
	ret := _m.Called(userid)

	var r0 *shopping.ShoppCart
	if rf, ok := ret.Get(0).(func(string) *shopping.ShoppCart); ok {
		r0 = rf(userid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*shopping.ShoppCart)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ModifyItemInShopCart provides a mock function with given fields: cartId, item, userid
func (_m *Service) ModifyItemInShopCart(cartId string, item *shopping.DetailItemInShopCart, userid string) error {
	ret := _m.Called(cartId, item, userid)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *shopping.DetailItemInShopCart, string) error); ok {
		r0 = rf(cartId, item, userid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewItemInShopCart provides a mock function with given fields: cartId, item, userid
func (_m *Service) NewItemInShopCart(cartId string, item *shopping.DetailItemInShopCart, userid string) error {
	ret := _m.Called(cartId, item, userid)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *shopping.DetailItemInShopCart, string) error); ok {
		r0 = rf(cartId, item, userid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewShoppingCart provides a mock function with given fields: userid
func (_m *Service) NewShoppingCart(userid string) (*shopping.ShoppCart, error) {
	ret := _m.Called(userid)

	var r0 *shopping.ShoppCart
	if rf, ok := ret.Get(0).(func(string) *shopping.ShoppCart); ok {
		r0 = rf(userid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*shopping.ShoppCart)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
