name: Build and Deploy App

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: go test -v ./...
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: generate config file
      env:
        CONFIG: ${{secrets.APP_CONFIG}}
      run: |
        echo "$CONFIG" > ./.env

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: widyaadebagus/web-service-part3:1.0

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull widyaadebagus/web-service-part3:1.0; \
            docker rm -f web-service-part3; \
            docker run -d -p 8001:8000 --name web-service-part3 widyaadebagus/web-service-part3:1.0
  